# NUMPY + Scipy + Matplotlib

Librerías de cálculo científico

Numpy: librería que permite el manejo de arrays multidimensionales de forma muy eficiente
https://numpy.org/

Scipy: librería que dispone de algoritmos de optimización, integración, interpolación, cálculo de autovalores y autovectores, resolución de ecuaciones diferenciales, cálculos estadísticos, etc. 
Está integrado con Numpy. 
https://scipy.org/

Matplot: librería de representación gráfica. Está integrada con Numpy
https://matplotlib.org/


# Numpy


In [1]:
import numpy as np  #importamos numpy con el alias   np 

#Creación de un array unidimensional
v=np.array([1,2,3]) #array 1d de enteros
w=np.array([1.1, -2, 4e-2]) #array 1d de dígitos en doble precisión
u=np.array([0,1,2], dtype='float')
print("v= \n", v, "\n w=\n ", w, " \n u=\n ", u)

v= 
 [1 2 3] 
 w=
  [ 1.1  -2.    0.04]  
 u=
  [0. 1. 2.]


In [2]:
#creación de arrays multidimensionales. Trabajaremos sólo con matrices

A=np.array([ [1,2], [3,4] ]) #matriz de enteros
B=np.array([[5,6],[7,9]],dtype='float')
C=np.array([[1,2,3.],[4,5,6],[7,8,9]])

print("A=\n",A)
print("B=\n", B)
print("C=\n", C)

#Podemos crear arrays especiales
Z=np.zeros(3)
print("Z= \n", Z)
Z=np.zeros((2,2))
print("Z= \n", Z)
O=np.ones(3)
print("O= \n", O)
O=np.ones((2,2))
print("O= \n", O)

I=np.eye(3)
print("I=\n",I)

A=
 [[1 2]
 [3 4]]
B=
 [[5. 6.]
 [7. 9.]]
C=
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Z= 
 [0. 0. 0.]
Z= 
 [[0. 0.]
 [0. 0.]]
O= 
 [1. 1. 1.]
O= 
 [[1. 1.]
 [1. 1.]]
I=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#Se puede operar con arrays (de la misma dimension)
D = A + B  #suma elemento a elemento
print("D= \n", D)
D = A - B  #resta elemento a elemento
print("D= \n", D)
D = A * B  #multiplica elemento a elemento
print("D= \n", D)
D = A / B  #divide elemento a elemento
print("D= \n", D)

D=A**2 #potencia de cada elemento
print("D= \n", D)

D= 
 [[ 6.  8.]
 [10. 13.]]
D= 
 [[-4. -4.]
 [-4. -5.]]
D= 
 [[ 5. 12.]
 [21. 36.]]
D= 
 [[0.2        0.33333333]
 [0.42857143 0.44444444]]
D= 
 [[ 1  4]
 [ 9 16]]


In [4]:
#Producto escalar de dos vectores
v=np.array([1,2,3]) 
w=np.array([1.1, -2, 4.e-2])
a=np.dot(v,w)
print("Producto escalar = ", a)

Producto escalar =  -2.78


In [5]:
#Multiplicar matriz por vector
A=np.array([[1,2,3.],[4,5,6],[7,8,9]])
v=np.array([1,2,3.5])
print( " A@v= \n", A@v)

 A@v= 
 [15.5 35.  54.5]


In [6]:
#Multiplicar dos matrices
A=np.array([[1.5,2,3.],[4,5.7,6],[7,8,9]])
B=np.array([[0,-1,3.],[1,0,6],[3,0,-2]])
print(A@B)

[[11.  -1.5 10.5]
 [23.7 -4.  34.2]
 [35.  -7.  51. ]]


In [7]:
#acceder elementos de un array 1d
# v[i]  accede al elemento i-ésimo del vector v. Los índices empiezan a contar desde 0
v=np.array([1,2.1,3])
print(v[0], v[1], v[2])
print(np.shape(v))
print(np.size(v))

#recorro todos los elementos del array en un bucle
for i in range(0, np.size(v)):
    print(v[i],"\t")
    
    
#acceso desde la última posición
print(v[-1]) #último elemento
print(v[-2])


1.0 2.1 3.0
(3,)
3
1.0 	
2.1 	
3.0 	
3.0
2.1


In [8]:
#acceder a elementos de un array 2d, m x n 
# A[i,j] accede al elemento de la i-ésima fija y j-ésima columna. Los índices empiezan a contar desde 0
A=np.array([[1,2,3.,0],[4,5,6,1],[7,8,9,5]])
print("A=", A)
m,n=np.shape(A)
print( "m, n = ", m,", ",n)

# extraigo todos los elementos de la i-ésima fila, A[i,:]
print("A[0,:]=", A[0,:])
print("A[1,:]=", A[1,:])
print("A[2,:]=", A[2,:])
#print("A[3,:]=", A[3,:]) #me paso de las dimensiones, porque empiezo en 0

#extraigo en un bucle las distintas filas
print("filas")
for i in range(0,m):
    print(A[i,:])
    
    
# extraigo todos los elemenots de la j-ésima columna, A[:,j]
print("columnas")
for j in range(0,n):
    print(A[:,j])


#accedo a la última fila
print("ultima fila= ", A[-1,:])
#accedo a la última columna
print("ultima columna= ",A[:,-1])

A= [[1. 2. 3. 0.]
 [4. 5. 6. 1.]
 [7. 8. 9. 5.]]
m, n =  3 ,  4
A[0,:]= [1. 2. 3. 0.]
A[1,:]= [4. 5. 6. 1.]
A[2,:]= [7. 8. 9. 5.]
filas
[1. 2. 3. 0.]
[4. 5. 6. 1.]
[7. 8. 9. 5.]
columnas
[1. 4. 7.]
[2. 5. 8.]
[3. 6. 9.]
[0. 1. 5.]
ultima fila=  [7. 8. 9. 5.]
ultima columna=  [0. 1. 5.]


In [9]:
#extraer submatrices
A=np.array([[1,2,3.,0],[4,5,6,1],[7,8,9,5]])
m,n=np.shape(A)
#extraigo toda las filas 1 y 2
print(A[1:3,:])
#extraigo fijas 1 y 2 y columnas 2 y 3
print(A[1:3,2:4])

[[4. 5. 6. 1.]
 [7. 8. 9. 5.]]
[[6. 1.]
 [9. 5.]]


In [10]:
#ojo con los typecasting

A=np.array([[1.5,2.23,3.],[4,5.e5,6],[7,8,9]])
B=np.array([[0,-1.25,3.],[1,0,6],[3,0,-2]])
m,n=np.shape(A)
C=np.zeros((m,n), dtype='int')
D=A@B
print("D= \n", D)
C[0,1]=D[0,1]
m,n=D.shape
for i in range(0,m):
    for j in range(0,n):
        C[i,j]=D[i,j]
print("C\n", C)

D= 
 [[ 1.12300e+01 -1.87500e+00  1.18800e+01]
 [ 5.00018e+05 -5.00000e+00  3.00000e+06]
 [ 3.50000e+01 -8.75000e+00  5.10000e+01]]
C
 [[     11      -1      11]
 [ 500018      -5 3000000]
 [     35      -8      51]]


In [11]:
#copiar el contenido de un array en otro array
v=np.array([1,2,3]) 
w=v  #Ojo!! ahora w y v apuntan a la misma dirección de memoria. Si hago un cambio en uno se hace en el otro 
print("w, v = ", w, v)
w[0]=-100.5
print("w, v = ", w, v)
print("w is v ",w is v)
#copiamos contenido
u=np.copy(v)  #ahora son dos arrays distintos. No apuntan a la misma dirección de memoria. Si cambio uno no cambia el otro
print("u, v = ", u, v)
u[-1]=-500.5  #como es un array de enteros, está redondeando. cuidado con problemas de este tipo
print("u, v = ", u, v)
print("u is v  ", u is v)

w, v =  [1 2 3] [1 2 3]
w, v =  [-100    2    3] [-100    2    3]
w is v  True
u, v =  [-100    2    3] [-100    2    3]
u, v =  [-100    2 -500] [-100    2    3]
u is v   False


In [12]:
#Ampliar una matriz con un array 1d
A=np.array([[1,2,3.,0],[4,5,6,1],[7,8,9,5]])
v=np.array([0.9,-1.7,-2.6])
m,n=np.shape(A)
C=np.zeros((m,n+1))
C[:,0:n]=np.copy(A)
print("C= ", C)
C[:,-1]=np.copy(v)
print("C=", C)

C=  [[1. 2. 3. 0. 0.]
 [4. 5. 6. 1. 0.]
 [7. 8. 9. 5. 0.]]
C= [[ 1.   2.   3.   0.   0.9]
 [ 4.   5.   6.   1.  -1.7]
 [ 7.   8.   9.   5.  -2.6]]


In [13]:
#producto de matrices
A=np.array([[1,2,3.,0],[4,5,6,1],[7,8,9,5]])
B=np.array([[1.4,2.5,3.,0],[0,0,6,1.5],[7,8,0,5],[0,-1,-3,0]])
B=B.T #Traspuesta de B
print("B= ", B)
m1,n1=np.shape(A)
m2,n2=np.shape(B)
print(A.shape, B.shape)
C=np.zeros(A.shape)
C=A@B
print("A@B= ", A@B)
print("shape -> ", np.shape(C))
D=np.zeros((m1,n2))

for i in range(0,m1):
    for j in range(0,n2):
        D[i,j]=np.dot(A[i,:], B[:,j])

print("D= ", D)

#True if two arrays have the same shape and elements, False otherwise.
print("C y D son iguales= ", np.array_equal(C,D))  

#Returns True if two arrays are element-wise equal within a tolerance.
print("C y D estan proximos, ", np.allclose(C,D, atol=1.e-20)) 

B=  [[ 1.4  0.   7.   0. ]
 [ 2.5  0.   8.  -1. ]
 [ 3.   6.   0.  -3. ]
 [ 0.   1.5  5.   0. ]]
(3, 4) (4, 4)
A@B=  [[ 15.4  18.   23.  -11. ]
 [ 36.1  37.5  73.  -23. ]
 [ 56.8  61.5 138.  -35. ]]
shape ->  (3, 4)
D=  [[ 15.4  18.   23.  -11. ]
 [ 36.1  37.5  73.  -23. ]
 [ 56.8  61.5 138.  -35. ]]
C y D son iguales=  True
C y D estan proximos,  True
